<a href="https://colab.research.google.com/github/mukhamedin67/bigdata67/blob/main/bigdata67_pracrice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

n = 1_000_000

data = np.random.randint(1, 100, size=(n, 5))

print("Массив өлшемі:", data.shape)
print("Алғашқы 10 жазба:")
print(data[:10])
print("Соңғы 10 жазба:")
print(data[-10:])

Массив өлшемі: (1000000, 5)
Алғашқы 10 жазба:
[[33 72 73 32 81]
 [16 80  2 48 40]
 [83 99 10 62 79]
 [90 27 56 88 74]
 [49  5 15 36 16]
 [98 60 11 34 71]
 [35 92 72 29 54]
 [87 89 94 87 29]
 [57  9 19 83  6]
 [69  8 44 43 94]]
Соңғы 10 жазба:
[[64 88 15 39 52]
 [ 4 64 72 60 10]
 [49 50 28 96 24]
 [90 88 87 10  5]
 [20 64 35 72 91]
 [47 96 27 70 22]
 [34 72 10 90 46]
 [43 79 63 96 40]
 [36 65 46 25 99]
 [43 19 16 94 25]]


In [3]:
print("100000–100009 аралығындағы жазбалар:")
print(data[100000:100010])

print("\nСатып алу сомасы мен тауар саны:")
print(data[:, [0, 1]])

print("\nӘр бағанның минималды мәні:")
print(np.min(data, axis=0))

print("\nӘр бағанның максималды мәні:")
print(np.max(data, axis=0))

print("\nБірінші бағанның орташа мәні:")
print(np.mean(data[:, 0]))

100000–100009 аралығындағы жазбалар:
[[28 75 10 62 75]
 [69  3  7 19 58]
 [17 71 15 10 43]
 [98 76 61 59 89]
 [72 66 88 43 92]
 [54 77 42 82 47]
 [44  6 53 43  6]
 [40 84 85 43  1]
 [11 23 83 48 68]
 [30 48 83  4 92]]

Сатып алу сомасы мен тауар саны:
[[33 72]
 [16 80]
 [83 99]
 ...
 [43 79]
 [36 65]
 [43 19]]

Әр бағанның минималды мәні:
[1 1 1 1 1]

Әр бағанның максималды мәні:
[99 99 99 99 99]

Бірінші бағанның орташа мәні:
49.993547


In [4]:
import numpy as np

print("Алғашқы 1000 жазба:")
first_1000 = data[:1000]
print(first_1000)

print("\nӘр 10-жазба:")
every_10 = data[::10]
print(every_10)

print("\nСоңғы 5000 жазба:")
last_5000 = data[-5000:]
print(last_5000)

print("\n2–5 бағандар:")
columns_2_5 = data[:, 1:5]
print(columns_2_5)

print("\nБаға, жеңілдік және салық бағандары:")
selected_columns = data[:, [0, 2, 4]]
print(selected_columns)

print("\n100000–200000 аралығындағы жазбалар:")
new_data = data[100000:200001]
print(new_data)

print("\nЖаңа деректер жиынының өлшемі:")
print(new_data.shape)

Алғашқы 1000 жазба:
[[33 72 73 32 81]
 [16 80  2 48 40]
 [83 99 10 62 79]
 ...
 [86 34 89 29 98]
 [43 35 64 39 83]
 [54 50 95 85 12]]

Әр 10-жазба:
[[33 72 73 32 81]
 [73 42 97 29 39]
 [54 13 20 96 69]
 ...
 [77 19  4 30 52]
 [43 35 59 52 62]
 [64 88 15 39 52]]

Соңғы 5000 жазба:
[[22 88 66  1 20]
 [90 64 63 78 10]
 [24 48 25 71 33]
 ...
 [43 79 63 96 40]
 [36 65 46 25 99]
 [43 19 16 94 25]]

2–5 бағандар:
[[72 73 32 81]
 [80  2 48 40]
 [99 10 62 79]
 ...
 [79 63 96 40]
 [65 46 25 99]
 [19 16 94 25]]

Баға, жеңілдік және салық бағандары:
[[33 73 81]
 [16  2 40]
 [83 10 79]
 ...
 [43 63 40]
 [36 46 99]
 [43 16 25]]

100000–200000 аралығындағы жазбалар:
[[28 75 10 62 75]
 [69  3  7 19 58]
 [17 71 15 10 43]
 ...
 [ 2  2 34 29 15]
 [77 32 89 28 64]
 [43  9 17  8 13]]

Жаңа деректер жиынының өлшемі:
(100001, 5)


In [5]:

import numpy as np

# Сатып алу сомалары
purchases = np.array([
    5000, 7000, 8000, 6000, 9000,
    7500, 8500, 6500, 10000, 500000
])

# Орташа мән
mean = np.mean(purchases)

# Стандартты ауытқу
std = np.std(purchases)

# Z-score есептеу
z_scores = (purchases - mean) / std

# Аномалияларды анықтау
anomalies = purchases[np.abs(z_scores) > 2]

print("Орташа мән:", mean)
print("Стандартты ауытқу:", std)
print("Z-score:", z_scores)
print("Аномалиялар:", anomalies)

# Аномалиялардың индекстерін табу
anomaly_indices = np.where(np.abs(z_scores) > 2)[0]

print("Аномалиялардың индекстері:", anomaly_indices)

# Аномалияларды алып тастау
clean_data = purchases[np.abs(z_scores) <= 2]

print("Тазаланған деректер:", clean_data)

# Тазалаудан кейінгі орташа мән
new_mean = np.mean(clean_data)

print("Тазалауға дейінгі орташа мән:", mean)
print("Тазалаудан кейінгі орташа мән:", new_mean)

Орташа мән: 56750.0
Стандартты ауытқу: 147756.59883741234
Z-score: [-0.35023816 -0.33670239 -0.3299345  -0.34347028 -0.32316662 -0.33331845
 -0.32655056 -0.34008633 -0.31639873  2.99986602]
Аномалиялар: [500000]
Аномалиялардың индекстері: [9]
Тазаланған деректер: [ 5000  7000  8000  6000  9000  7500  8500  6500 10000]
Тазалауға дейінгі орташа мән: 56750.0
Тазалаудан кейінгі орташа мән: 7500.0


In [6]:

import numpy as np

# 4 аймақ, 12 ай, 30 күн бойынша сатылым деректері
sales = np.random.randint(
    1000,
    50000,
    size=(4, 12, 30)
)

print("Массив өлшемі:", sales.shape)

# 1. Бірінші аймақтың барлық деректері
print("\n1. Бірінші аймақтың барлық деректері:")
print(sales[0])

# 2. Үшінші аймақтың 5-айдағы барлық күндік сатылымдары
print("\n2. Үшінші аймақтың 5-айдағы сатылымдары:")
print(sales[2, 4, :])

# 3. Барлық аймақтардың бірінші айдағы сатылымдары
print("\n3. Барлық аймақтардың бірінші айдағы сатылымдары:")
print(sales[:, 0, :])

# 4. Бірінші және екінші аймақтардың деректері
print("\n4. Бірінші және екінші аймақтардың деректері:")
print(sales[0:2])

# 5. Әр аймақ бойынша жылдық сатылым көлемі
print("\n5. Әр аймақ бойынша жылдық сатылым:")
print(np.sum(sales, axis=(1, 2)))

# 6. Әр ай бойынша барлық аймақтардың сатылымы
print("\n6. Әр ай бойынша барлық аймақтардың сатылымы:")
print(np.sum(sales, axis=(0, 2)))

# 7. Әр аймақтың ең жоғары күндік сатылымы
print("\n7. Әр аймақтың ең жоғары күндік сатылымы:")
print(np.max(sales, axis=(1, 2)))

# 8. Әр аймақтың ең төменгі күндік сатылымы
print("\n8. Әр аймақтың ең төменгі күндік сатылымы:")
print(np.min(sales, axis=(1, 2)))

Массив өлшемі: (4, 12, 30)

1. Бірінші аймақтың барлық деректері:
[[45236 40772 28078 11619 49358 22829 19708 48935 13656 46309  4821 23554
  18408 15914 40599 28461 11183  9208 23530 22641 31962 25336 14882 37550
  18767 33759  6641 13503  5872  9773]
 [36683  8126 25697 13477 19962 34174 24835 27522 22234 15362 46112 21898
  16619 38554 45906 14255 48745 12413  3916 46630 43019  7120 45265 35164
   3107 18298 10300 18900 16247 20756]
 [28176 37672 30186  4751 10685 47453 23462 22359 23141 30930 30225 20203
  47853 29193 10893 15200 42972 38560 37065 25488 31425 26110 25328 16264
   8784 15893 22222  4354 21182 30049]
 [ 1650  8431 12023  4670  6750 23275 12117 27837  2920  5421 46125 39596
  46104 24394 34619  7799 28801 27935 11446 35028  3167  7391 35175 20978
  44964 15353 10912 10667 22530 22307]
 [14528 32566 22424 21164 18275 49890 47470 43478  1244 30092 24401 16787
  23214 24902  4082  3908 15021 43265 43440  5847  5778  8014  4892 37760
  21174 38216 38139  8805 10146 12728]

In [7]:

import numpy as np

# 1 миллион транзакция құру
n = 1_000_000

np.random.seed(42)

# Клиент ID
client_id = np.random.randint(1, 90001, n)

# Өнім ID
product_id = np.random.randint(1, 5000, n)

# Сатып алу сомасы
purchase_amount = np.random.randint(1000, 50001, n)

# Тауар саны
quantity = np.random.randint(1, 11, n)

# Жеңілдік мөлшері (%)
discount = np.random.randint(0, 31, n)

# Аймақ коды
region = np.random.randint(1, 5, n)

# Барлық бағандарды бір массивке біріктіру
transactions = np.column_stack((
    client_id,
    product_id,
    purchase_amount,
    quantity,
    discount,
    region
))

# Массивтің өлшемі мен құрылымы
print("Массив өлшемі:", transactions.shape)

print("\nБағандар:")
print("Клиент ID | Өнім ID | Сатып алу сомасы | Тауар саны | Жеңілдік (%) | Аймақ коды")

print("\nАлғашқы 10 транзакция:")
print(transactions[:10])

print("\nДеректер түрі:")
print(transactions.dtype)

print("\nТранзакциялар саны:")
print(len(transactions))

Массив өлшемі: (1000000, 6)

Бағандар:
Клиент ID | Өнім ID | Сатып алу сомасы | Тауар саны | Жеңілдік (%) | Аймақ коды

Алғашқы 10 транзакция:
[[15796  2136 12126     8    27     1]
 [  861   517 44273     4    12     4]
 [76821  1531 40968     6    24     1]
 [54887  3514 48400     4    23     1]
 [ 6266  3154 36922     1    25     4]
 [82387   358 38473     4    16     1]
 [37195  3903 30747     3     0     2]
 [87499   392 41859     2    16     4]
 [44132  2851 27311     1    28     3]
 [60264  2569 31821     6     2     4]]

Деректер түрі:
int64

Транзакциялар саны:
1000000


In [8]:
import numpy as np

# 1. Деректердің көшірмесін құру
working_data = transactions.astype(float).copy()

# 2. Қайталанатын жазбаларды модельдеу
working_data[100:110] = working_data[0:10]

# Қайталанатын жазбаларды анықтау
unique_rows, counts = np.unique(
    working_data, axis=0, return_counts=True
)

duplicates = unique_rows[counts > 1]

print("Қайталанатын жазбалар саны:", np.sum(counts - 1))
print("Қайталанатын жазбалар:")
print(duplicates)

# 3. Жетіспейтін мәндерді модельдеу
working_data[20, 2] = np.nan
working_data[21, 4] = np.nan
working_data[22, 3] = np.nan

# Жетіспейтін мәндерді анықтау
missing_values = np.isnan(working_data)

print("\nЖетіспейтін мәндер саны:", np.sum(missing_values))
print("Әр бағандағы жетіспейтін мәндер:")
print(np.sum(missing_values, axis=0))

print("\nЖетіспейтін мәндері бар жазбалар:")
print(working_data[np.any(missing_values, axis=1)])

# 4. Қате және шектен тыс мәндерді модельдеу
working_data[30, 2] = -5000
working_data[31, 3] = 0
working_data[32, 2] = 5000000

# 5. Қате мәндерді анықтау
invalid_data = working_data[
    (working_data[:, 2] < 0) |
    (working_data[:, 3] <= 0)
]

print("\nҚате мәндері бар жазбалар:")
print(invalid_data)

print("\nҚате жазбалар саны:", len(invalid_data))

# 6. Шектен тыс мәндерді анықтау
outliers = working_data[working_data[:, 2] > 50000]

print("\nШектен тыс сатып алу сомалары:")
print(outliers)

print("\nШектен тыс мәндер саны:", len(outliers))

# 7. Деректер жиынының өлшемі
print("\nДеректер жиынының өлшемі:", working_data.shape)

Қайталанатын жазбалар саны: 10
Қайталанатын жазбалар:
[[8.6100e+02 5.1700e+02 4.4273e+04 4.0000e+00 1.2000e+01 4.0000e+00]
 [6.2660e+03 3.1540e+03 3.6922e+04 1.0000e+00 2.5000e+01 4.0000e+00]
 [1.5796e+04 2.1360e+03 1.2126e+04 8.0000e+00 2.7000e+01 1.0000e+00]
 [3.7195e+04 3.9030e+03 3.0747e+04 3.0000e+00 0.0000e+00 2.0000e+00]
 [4.4132e+04 2.8510e+03 2.7311e+04 1.0000e+00 2.8000e+01 3.0000e+00]
 [5.4887e+04 3.5140e+03 4.8400e+04 4.0000e+00 2.3000e+01 1.0000e+00]
 [6.0264e+04 2.5690e+03 3.1821e+04 6.0000e+00 2.0000e+00 4.0000e+00]
 [7.6821e+04 1.5310e+03 4.0968e+04 6.0000e+00 2.4000e+01 1.0000e+00]
 [8.2387e+04 3.5800e+02 3.8473e+04 4.0000e+00 1.6000e+01 1.0000e+00]
 [8.7499e+04 3.9200e+02 4.1859e+04 2.0000e+00 1.6000e+01 4.0000e+00]]

Жетіспейтін мәндер саны: 3
Әр бағандағы жетіспейтін мәндер:
[0 0 1 1 1 0]

Жетіспейтін мәндері бар жазбалар:
[[8.3105e+04 3.1560e+03        nan 2.0000e+00 1.2000e+01 1.0000e+00]
 [5.3708e+04 7.9700e+02 4.7057e+04 5.0000e+00        nan 4.0000e+00]
 [8.530

In [9]:
# Жетіспейтін мәндерді орташа мәнмен толтыру
clean_data = working_data.copy()

for col in range(clean_data.shape[1]):
    mean_value = np.nanmean(clean_data[:, col])
    clean_data[np.isnan(clean_data[:, col]), col] = mean_value

print("Жетіспейтін мәндер саны:")
print(np.isnan(clean_data).sum())

print("\nТазаланған деректер:")
print(clean_data[:10])

Жетіспейтін мәндер саны:
0

Тазаланған деректер:
[[1.5796e+04 2.1360e+03 1.2126e+04 8.0000e+00 2.7000e+01 1.0000e+00]
 [8.6100e+02 5.1700e+02 4.4273e+04 4.0000e+00 1.2000e+01 4.0000e+00]
 [7.6821e+04 1.5310e+03 4.0968e+04 6.0000e+00 2.4000e+01 1.0000e+00]
 [5.4887e+04 3.5140e+03 4.8400e+04 4.0000e+00 2.3000e+01 1.0000e+00]
 [6.2660e+03 3.1540e+03 3.6922e+04 1.0000e+00 2.5000e+01 4.0000e+00]
 [8.2387e+04 3.5800e+02 3.8473e+04 4.0000e+00 1.6000e+01 1.0000e+00]
 [3.7195e+04 3.9030e+03 3.0747e+04 3.0000e+00 0.0000e+00 2.0000e+00]
 [8.7499e+04 3.9200e+02 4.1859e+04 2.0000e+00 1.6000e+01 4.0000e+00]
 [4.4132e+04 2.8510e+03 2.7311e+04 1.0000e+00 2.8000e+01 3.0000e+00]
 [6.0264e+04 2.5690e+03 3.1821e+04 6.0000e+00 2.0000e+00 4.0000e+00]]


In [10]:

# Қайталанатын жазбаларды жою
before = len(clean_data)

clean_data = np.unique(clean_data, axis=0)

after = len(clean_data)

print("Тазалауға дейінгі жазбалар саны:", before)
print("Тазалаудан кейінгі жазбалар саны:", after)
print("Жойылған қайталанатын жазбалар саны:", before - after)

print("\nЖаңа массив өлшемі:", clean_data.shape)

Тазалауға дейінгі жазбалар саны: 1000000
Тазалаудан кейінгі жазбалар саны: 999990
Жойылған қайталанатын жазбалар саны: 10

Жаңа массив өлшемі: (999990, 6)


In [11]:

# Қажетті бағандарды бөліп алу
selected_data = clean_data[:, [0, 2, 3]]

print("Клиент ID | Сатып алу сомасы | Тауар саны")
print(selected_data[:10])

print("\nЖаңа массив өлшемі:")
print(selected_data.shape)

Клиент ID | Сатып алу сомасы | Тауар саны
[[1.0000e+00 2.2495e+04 4.0000e+00]
 [1.0000e+00 1.8903e+04 2.0000e+00]
 [1.0000e+00 3.4394e+04 4.0000e+00]
 [1.0000e+00 7.7960e+03 5.0000e+00]
 [1.0000e+00 3.2256e+04 9.0000e+00]
 [1.0000e+00 4.4959e+04 9.0000e+00]
 [1.0000e+00 2.8872e+04 1.0000e+00]
 [1.0000e+00 2.3794e+04 6.0000e+00]
 [2.0000e+00 7.4230e+03 4.0000e+00]
 [2.0000e+00 4.0440e+04 8.0000e+00]]

Жаңа массив өлшемі:
(999990, 3)


In [12]:

# Сатып алу сомасы 30000 теңгеден жоғары транзакциялар
filtered_data = clean_data[clean_data[:, 2] > 30000]

print("Сатып алу сомасы 30000 теңгеден жоғары транзакциялар:")
print(filtered_data[:10])

print("\nСүзгіленген транзакциялар саны:")
print(len(filtered_data))

print("\nЖаңа массив өлшемі:")
print(filtered_data.shape)

Сатып алу сомасы 30000 теңгеден жоғары транзакциялар:
[[1.0000e+00 1.6460e+03 3.4394e+04 4.0000e+00 3.0000e+00 3.0000e+00]
 [1.0000e+00 2.3890e+03 3.2256e+04 9.0000e+00 2.9000e+01 4.0000e+00]
 [1.0000e+00 2.6170e+03 4.4959e+04 9.0000e+00 2.3000e+01 3.0000e+00]
 [2.0000e+00 4.2600e+02 4.0440e+04 8.0000e+00 1.2000e+01 1.0000e+00]
 [2.0000e+00 1.2390e+03 3.7009e+04 6.0000e+00 2.4000e+01 3.0000e+00]
 [3.0000e+00 7.2700e+02 4.5739e+04 1.0000e+01 2.9000e+01 4.0000e+00]
 [3.0000e+00 8.9700e+02 4.3525e+04 6.0000e+00 1.3000e+01 4.0000e+00]
 [3.0000e+00 1.5160e+03 3.7081e+04 9.0000e+00 2.5000e+01 1.0000e+00]
 [3.0000e+00 2.3070e+03 4.9733e+04 6.0000e+00 5.0000e+00 3.0000e+00]
 [3.0000e+00 4.2450e+03 4.0402e+04 7.0000e+00 2.0000e+00 1.0000e+00]]

Сүзгіленген транзакциялар саны:
408284

Жаңа массив өлшемі:
(408284, 6)


In [13]:

# Жалпы табысты есептеу
total_income = np.sum(clean_data[:, 2] * (1 - clean_data[:, 4] / 100))

print("Жалпы табыс:", total_income, "теңге")

Жалпы табыс: 21684906870.464436 теңге


In [14]:

# Әр клиенттің орташа сатып алу сомасы
client_ids, inverse = np.unique(
    clean_data[:, 0], return_inverse=True
)

total_amount = np.bincount(
    inverse, weights=clean_data[:, 2]
)

purchase_count = np.bincount(inverse)

average_amount = total_amount / purchase_count

print("Клиент ID | Орташа сатып алу сомасы")

print(np.column_stack((
    client_ids, average_amount
))[:10])

Клиент ID | Орташа сатып алу сомасы
[[1.00000000e+00 2.66836250e+04]
 [2.00000000e+00 1.98288750e+04]
 [3.00000000e+00 3.20555000e+04]
 [4.00000000e+00 2.81450000e+04]
 [5.00000000e+00 3.07315000e+04]
 [6.00000000e+00 2.65624286e+04]
 [7.00000000e+00 1.71448333e+04]
 [8.00000000e+00 2.58980000e+04]
 [9.00000000e+00 2.91158889e+04]
 [1.00000000e+01 1.88617500e+04]]


In [15]:

# Әр аймақтың сатылым көлемін есептеу
region_ids, inverse = np.unique(
    clean_data[:, 5], return_inverse=True
)

region_sales = np.bincount(
    inverse,
    weights=clean_data[:, 2]
)

print("Аймақ коды | Жалпы сатылым сомасы")

print(np.column_stack((
    region_ids, region_sales
)))

print("\nСатылым көлемі ең жоғары аймақ:")
print(region_ids[np.argmax(region_sales)])

print("\nЕң жоғары сатылым сомасы:")
print(np.max(region_sales))

Аймақ коды | Жалпы сатылым сомасы
[[1.00000000e+00 6.37993515e+09]
 [2.00000000e+00 6.37161338e+09]
 [3.00000000e+00 6.39152758e+09]
 [4.00000000e+00 6.37407140e+09]]

Сатылым көлемі ең жоғары аймақ:
3.0

Ең жоғары сатылым сомасы:
6391527584.0


In [16]:

# Сатып алу сомасының орташа мәні
mean_amount = np.mean(clean_data[:, 2])

# Сатып алу сомасының медианасы
median_amount = np.median(clean_data[:, 2])

print("Орташа сатып алу сомасы:", mean_amount)
print("Медиана:", median_amount)

Орташа сатып алу сомасы: 25517.402692527347
Медиана: 25531.0


In [17]:

# Минималды және максималды сатып алу сомасы
min_amount = np.min(clean_data[:, 2])
max_amount = np.max(clean_data[:, 2])

print("Минималды сатып алу сомасы:", min_amount)
print("Максималды сатып алу сомасы:", max_amount)

Минималды сатып алу сомасы: -5000.0
Максималды сатып алу сомасы: 5000000.0


In [18]:

# Сатып алу сомасының стандартты ауытқуы
std_amount = np.std(clean_data[:, 2])

print("Стандартты ауытқу:", std_amount)

Стандартты ауытқу: 14996.481865578544


In [19]:

# Сатып алу сомасының квартильдері
quartiles = np.percentile(clean_data[:, 2], [25, 50, 75])

print("Q1 (25%):", quartiles[0])
print("Q2 (50%):", quartiles[1])
print("Q3 (75%):", quartiles[2])

Q1 (25%): 13243.0
Q2 (50%): 25531.0
Q3 (75%): 37762.0


In [20]:

# Z-score арқылы аномалияларды анықтау
z_scores = (clean_data[:, 2] - mean_amount) / std_amount

anomalies = clean_data[np.abs(z_scores) > 3]

print("Аномалиялар саны:", len(anomalies))

print("\nАномалия анықталған жазбалар:")
print(anomalies[:10])

Аномалиялар саны: 1

Аномалия анықталған жазбалар:
[[3.5774e+04 1.5760e+03 5.0000e+06 9.0000e+00 2.0000e+01 3.0000e+00]]


In [21]:

# Тазалауға дейінгі орташа мән
before_mean = np.nanmean(working_data[:, 2])

# Тазалаудан кейінгі орташа мән
after_mean = np.mean(clean_data[:, 2])

print("Тазалауға дейінгі орташа мән:", before_mean)
print("Тазалаудан кейінгі орташа мән:", after_mean)

print("\nОрташа мәннің өзгерісі:", after_mean - before_mean)

print("\nТазалауға дейінгі жазбалар саны:", len(working_data))
print("Тазалаудан кейінгі жазбалар саны:", len(clean_data))

Тазалауға дейінгі орташа мән: 25517.500418500418
Тазалаудан кейінгі орташа мән: 25517.402692527347

Орташа мәннің өзгерісі: -0.09772597307164688

Тазалауға дейінгі жазбалар саны: 1000000
Тазалаудан кейінгі жазбалар саны: 999990
